spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/kirana_register
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

server:
  port: 8081

jwt:
  secret: "mysecretkey"
  expiration: 3600000  # 1 hour

logging:
  level:
    org.springframework: INFO
